In [1]:
from scipy.stats import ks_2samp

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [5]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
result1 = ks_2samp(arr1,arr2)

In [18]:
result1

KstestResult(statistic=0.0, pvalue=1.0)

### Giving pvalue = 1.0 which meane distribution of these two sets are exactly same 

In [8]:
## Now take another dataset
arr3 = np.arange(10,20)

In [9]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
result2 = ks_2samp(arr1,arr3)

In [15]:
result2

KstestResult(statistic=1.0, pvalue=1.0825088224469026e-05)

### Giving P-value equals to zero which means distribution of these two sets is not same or different

In [19]:
round(result2.pvalue)

0